apiVersion: apps/v1
kind: Deployment
metadata:
  name: stringgenerator-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stringgenerator
  template:
    metadata:
      labels:
        app: stringgenerator
    spec:
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: log-output-claim
      - name: config-volume
        configMap:
          name: log-config
      containers:
      - name: generator
        image: vilhopul/mooc-kube-vm:1.10.generator
        imagePullPolicy: Always
        volumeMounts:
        - name: log-volume
          mountPath: /usr/src/app/files
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
      - name: reader
        image: vilhopul/mooc-kube-vm:4.1.reader
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: log-volume
          mountPath: /usr/src/app/files
        - name: config-volume
          mountPath: /config
          readOnly: true
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PORT
          value: "8090"
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-config
              key: MESSAGE
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5