apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
  namespace: exercises
data:
  MESSAGE: "hello from config map"
  information.txt: |
    This is from the infromation.txt file that I just created!