apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-claim
  namespace: exercises
spec:
  storageClassName: temp-kube-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi