apiVersion: v1
kind: Service
metadata:
  name: stringgenerator-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: stringgenerator
  ports:
  - port: 2345
    protocol: TCP
    targetPort: 8090