apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-web-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-web-server
  template:
    metadata:
      labels:
        app: kube-web-server
    spec:
      volumes:
      - name: project-volume
        persistentVolumeClaim:
          claimName: project-claim
      containers:
      - name: kube-web-server
        image: vilhopul/mooc-kube-vm:2.2.webserver
        imagePullPolicy: Always
        volumeMounts:
        - name: project-volume
          mountPath: /usr/src/app/files
        env:
        - name: PORT
          value: "8080"