apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-web-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-web-server
  template:
    metadata:
      labels:
        app: kube-web-server
    spec:
      containers:
      - name: kube-web-server
        image: vilhopul/mooc-kube-vm:1.5
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"