apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - deployment.yaml
  - service.yaml
  - persistantvolumeclaim.yaml
  - ingress.yaml
  - gateway.yaml

images:
  - name: kube-web-server-dep
    newName: kube-web-server-dep
    newTag: latest