apiVersion: v1
kind: Service
metadata:
  name: kube-web-server-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: kube-web-server
  ports:
  - port: 1234
    protocol: TCP
    targetPort: 8080