apiVersion: v1
kind: Service
metadata:
  name: kube-web-server-svc
spec:
  type: NodePort
  selector:
    app: kube-web-server
  ports:
  - name: http
    nodePort: 30080
    protocol: TCP
    port: 1234
    targetPort: 8080