apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - deployment.yaml
  - service.yaml
  - database.yaml
  - cronjob.yaml
  - backup-cronjob.yaml
images:
  - name: todo-backend-dep
    newName: todo-backend-dep
    newTag: latest