apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces
  - ../../PVs
  - ../../web_server/manifests
  - ../../todo-backend/manifests

images:
  - name: WEB_SERVER_IMAGE
    newName: vilhopul/mooc-kube-vm
    newTag: 2.6.webserver
  - name: TODO_BACKEND_IMAGE
    newName: vilhopul/mooc-kube-vm
    newTag: 2.10.todobackend